name: Push Docker Image to Azure Container Registry
  on: [push]
  permissions:
    id-token: write
    contents: read

  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
      # - name: 'Az CLI login'
      #   uses: azure/login@v1
      #   with:
      #       client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Login to the Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: mdmichaelregistry.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      - name: Docker meta
          id: meta
          uses: docker/metadata-action@v3
          with:
            flavor: |
              latest=true
            images: mdmichaelregistry.azurecr.io/${{ github.repository }}
            tags: |
              type=ref,event=branch
              type=sha
        - name: Build and push
          id: docker-build
          uses: docker/build-push-action@v2
          with:
            file: Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
